### PR TITLE
Prepare Squot for CI

### PR DESCRIPTION
**Pull request by fniephaus**
I'm not sure if removing the `monticello.meta` causes any harm to your integration, but it was necessary to be able to load it into a clean image. Otherwise, Metacello didn't recognize that the packages were exported with metadata-less Filetree.
As soon as you turn on TravisCI and AppVeyor for this repository, Squot should be loaded and tested in a Squeak-trunk image.

Fabio

### CODE REVIEW

**Comment by j4yk** [comment]
Well, the Cypress writers will create that directory again. It is the reason why I require the latest version of FileTree because it checks for the version file's presence in monticello.meta, instead of the directory's presence. I could load it in a fresh trunk image (after loading metacello-work, of course), but I'll have another look.

**Comment by fniephaus** [comment]
What exactly needs to be loaded before loading the baseline? `metacello-work`, `filetree`, or ...?

**Comment by j4yk** [comment]
Only metacello-work, filetree is required in the baseline itself.

**Comment by fniephaus** [comment]
Okay, I've reverted the commit that deleted all `monticello.meta` directories.
Also, I see that you have enabled Travis, cool! As a Windows user, you might also want to enable AppVeyor ;)

**Comment by fniephaus** [comment]
Okay, Travis can load Squot now and run the tests. I'll leave the rest up to you. You might want to for example bump the timeout (see [`#defaultTimeout `](https://github.com/hpi-swa/smalltalkCI#testcase-selection)).

**Comment by j4yk** [comment]
There is a problem with SqueakSSL.dll on Windows. I had to use cygwin's chmod u+x, otherwise it says Access Denied when the DLL shall be loaded. Is this a smalltalkCI issue?

**Comment by fniephaus** [comment]
This is the first time I hear about a problem with `SqueakSSL.dll`, but that's very much possible.
Did you have to chmod the dll or the exe?

**Comment by j4yk** [comment]
Hmm, I chmodded the entire vms folder in the cache. I will run a clean and try it with the dll only.

**Comment by j4yk** [comment]
Making only the dll executable suffices. The same probably applies to all other plugin dlls. Cygwin tries too hard to emulate the permission bits with Windows ACLs and explicitly denies the permission to execute these files.

**Comment by j4yk** [comment]
I am closing this, since the remaining errors are not related to how the CI is set up from the perspective of this repository. The test failures are mostly due to missing fixture setup or missing expectedFailures (all tests that push obviously require some git credentials, in particular my credentials).

**Comment by fniephaus** [comment]
That's too bad, Windows always needs some extra love.
I'm working on a fix for smalltalkCI.
But first, I need to wait until my Windows VM has finished updating itself 😵

**Comment by fniephaus** [comment]
Try again: https://github.com/hpi-swa/smalltalkCI/commit/4c7d41db04b1333d565c534c0a3d1d65f79c4fdd.

**Comment by j4yk** [comment]
It runs now. Got 0 failures and 19 errors, but I cannot see them in the console. Is it always like that?
https://ci.appveyor.com/project/j4yk/squot
Also, there an empty Tests tab in AppVeyor, but I suppose one has to do something special to puts one's test results there...

**Comment by fniephaus** [comment]
I have to look into this tomorrow. The image was closed for reason, probably because of an error.
You could also just clone smalltalkCI and start a local build with run.sh --headful.
smalltalkCI does not support this test tab, not sure how this even works.

**Comment by fniephaus** [comment]
Interestingly, [the last build](https://ci.appveyor.com/project/j4yk/squot/build/1.0.6) didn't have this problem. Let me know if it happens again. Very hard to find hardly reproducible bugs :(

**Pull request merged**
